import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from "next/font/google";
import { Space_Grotesk, Manrope } from 'next/font/google';
import './globals.css';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const manrope = Manrope({
   subsets: ['latin'], // Subset yang digunakan
   weight: ['400', '500', '700'], // Pilihan bobot font
   variable: '--font-manrope', // Variabel CSS untuk font
});

const spaceGrotesk = Space_Grotesk({
   subsets: ['latin'], // Subset font, sesuaikan dengan kebutuhan
   weight: ['400', '500', '700'], // Pilih bobot font
   variable: '--font-space-grotesk', // Variabel untuk CSS
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${spaceGrotesk.variable} ${manrope.variable} antialiased`}>{children}</body>
      </html>
   );
}
